In [8]:
#XINLEI HONG ICE5

In [9]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [10]:

# IRIS is included in sci-kit learn. We can directly load it.
# See documentation here: https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html
irisRaw = datasets.load_iris()

# Convert it to a pandas dataframe for better visualization
iris = pd.DataFrame(data=irisRaw.data, columns=irisRaw.feature_names)
iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
iris_MCAR = iris.copy()

In [12]:
# Set the missingness rate at 30%
missing = 0.3

# Only introduce missing rate to the `sepal length (cm)`.
iris_MCAR.loc[iris_MCAR.sample(frac=missing).index, 'sepal length (cm)'] = np.nan

iris_MCAR

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                NaN               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                NaN               3.4                5.4               2.3
149                NaN               3.0                5.1               1.8

[150 rows x 4 columns]

In [13]:
# Alternatively, iterate through all columns and introduce 20% missing to all variables.
for col in iris_MCAR.columns:
    iris_MCAR.loc[iris_MCAR.sample(frac=missing).index, col] = np.nan

In [14]:
iris_MAR = iris.copy()

In [15]:
# Set the missingness rate at 30%
missing = 0.3

# Only introduce missing rate to the `sepal length (cm)`.
iris_MAR.loc[iris_MAR.sample(frac=missing, weights = 'sepal width (cm)').index, 'sepal length (cm)'] = np.nan

iris_MAR

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  NaN               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                NaN               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [16]:
iris_MCAR_listwise = iris_MCAR.copy()
iris_MCAR_listwise.dropna()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
35                 5.0               3.2                1.2               0.2
38                 4.4               3.0                1.3               0.2
49                 5.0               3.3                1.4               0.2
67                 5.8               2.7                4.1               1.0
68                 6.2               2.2                4.5               1.5
77                 6.7               3.0                5.0               1.7
92                 5.8               2.6                4.0               1.2
93                 5.0               2.3                3.3               1.0
94                 5.6               2.7                4.2               1.3
104                6.5               3.0                5.8               2.2
112                6.8               3.0                5.5               2.1
118                7.7               2.6                6.9               2.3
121                5.6               2.8                4.9               2.0
125                7.2               3.2                6.0               1.8
130                7.4               2.8                6.1               1.9
133                6.3               2.8                5.1               1.5
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0

In [17]:
iris_MCAR_pairwise = iris_MCAR.copy()
iris_MAR_pairwise = iris_MAR.copy()

print("Mean estimation in MCAR data with pairwise deletion",
      iris_MCAR_pairwise['sepal length (cm)'].mean(), 
     "\nSD estimation in MCAR data with pairwise deletion",
      iris_MCAR_pairwise['sepal length (cm)'].std()
     )
print("Mean estimation in MAR data with pairwise deletion",
      iris_MAR_pairwise['sepal length (cm)'].mean(), 
     "\nSD estimation in MAR data with pairwise deletion",
      iris_MAR_pairwise['sepal length (cm)'].std()
     )
print("Mean estimation in the original data",
      iris['sepal length (cm)'].mean(),
      "\nSD estimation in the original data",
      iris['sepal length (cm)'].std()
     )

Mean estimation in MCAR data with pairwise deletion 5.770129870129868
SD estimation in MCAR data with pairwise deletion 0.8674015847504628
Mean estimation in MAR data with pairwise deletion 5.850476190476189
SD estimation in MAR data with pairwise deletion 0.845704509398003
Mean estimation in the original data 5.843333333333335
SD estimation in the original data 0.8280661279778629

In [18]:
from sklearn.impute import SimpleImputer
iris_MAR_mean = iris_MAR.copy()

In [19]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(iris_MAR)
print(imp.transform(iris_MAR))

[[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [4.6        3.1        1.5        0.2       ]
 [5.85047619 3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.3       ]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.9        3.1        1.5        0.1       ]
 [5.4        3.7        1.5        0.2       ]
 [5.85047619 3.4        1.6        0.2       ]
 [4.8        3.         1.4        0.1       ]
 [4.3        3.         1.1        0.1       ]
 [5.8        4.         1.2        0.2       ]
 [5.85047619 4.4        1.5        0.4       ]
 [5.4        3.9        1.3        0.4       ]
 [5.85047619 3.5        1.4        0.3       ]
 [5.85047619 3.8        1.7        0.3       ]
 [5.1        3.8        1.5        0.3       ]
 [5.85047619 3.4        1.7        0.2       ]
 [5.1        3.7        1.5        0.4       ]
 [4.6        3.6        1.         0.2       ]
 [5.85047619 3.3        1.7        0.5       ]
 [5.85047619 3.4        1.9        0.2       ]
 [5.         3.         1.6        0.2       ]
 [5.         3.4        1.6        0.4       ]
 [5.85047619 3.5        1.5        0.2       ]
 [5.2        3.4        1.4        0.2       ]
 [5.85047619 3.2        1.6        0.2       ]
 [4.8        3.1        1.6        0.2       ]
 [5.85047619 3.4        1.5        0.4       ]
 [5.2        4.1        1.5        0.1       ]
 [5.85047619 4.2        1.4        0.2       ]
 [4.9        3.1        1.5        0.2       ]
 [5.85047619 3.2        1.2        0.2       ]
 [5.5        3.5        1.3        0.2       ]
 [4.9        3.6        1.4        0.1       ]
 [5.85047619 3.         1.3        0.2       ]
 [5.1        3.4        1.5        0.2       ]
 [5.         3.5        1.3        0.3       ]
 [5.85047619 2.3        1.3        0.3       ]
 [4.4        3.2        1.3        0.2       ]
 [5.85047619 3.5        1.6        0.6       ]
 [5.1        3.8        1.9        0.4       ]
 [4.8        3.         1.4        0.3       ]
 [5.1        3.8        1.6        0.2       ]
 [4.6        3.2        1.4        0.2       ]
 [5.3        3.7        1.5        0.2       ]
 [5.85047619 3.3        1.4        0.2       ]
 [5.85047619 3.2        4.7        1.4       ]
 [6.4        3.2        4.5        1.5       ]
 [6.9        3.1        4.9        1.5       ]
 [5.5        2.3        4.         1.3       ]
 [6.5        2.8        4.6        1.5       ]
 [5.7        2.8        4.5        1.3       ]
 [6.3        3.3        4.7        1.6       ]
 [4.9        2.4        3.3        1.        ]
 [6.6        2.9        4.6        1.3       ]
 [5.2        2.7        3.9        1.4       ]
 [5.         2.         3.5        1.        ]
 [5.85047619 3.         4.2        1.5       ]
 [6.         2.2        4.         1.        ]
 [6.1        2.9        4.7        1.4       ]
 [5.85047619 2.9        3.6        1.3       ]
 [6.7        3.1        4.4        1.4       ]
 [5.6        3.         4.5        1.5       ]
 [5.8        2.7        4.1        1.        ]
 [6.2        2.2        4.5        1.5       ]
 [5.6        2.5        3.9        1.1       ]
 [5.9        3.2        4.8        1.8       ]
 [5.85047619 2.8        4.         1.3       ]
 [6.3        2.5        4.9        1.5       ]
 [6.1        2.8        4.7        1.2       ]
 [6.4        2.9        4.3        1.3       ]
 [6.6        3.         4.4        1.4       ]
 [6.8        2.8        4.8        1.4       ]
 [5.85047619 3.         5.         1.7       ]
 [5.85047619 2.9        4.5        1.5       ]
 [5.7        2.6        3.5        1.        ]
 [5.5        2.4        3.8        1.1       ]
 [5.5        2.4        3.7        1.        ]
 [5.8        2.7        3.9        1.2       ]
 [6.         2.7        5.1        1.6       ]
 [5.4        3.         4.5        1.5       ]
 [5.85047619 3.4        4.5        1.6       ]
 [5.85047619 3.1        4.7        1.5       ]
 [6.3        2.3        4.4        1.3       ]
 [5.6        3.         4.1        1.3       ]
 [5.5        2.5        4.         1.3       ]
 [5.85047619 2.6        4.4        1.2       ]
 [5.85047619 3.         4.6        1.4       ]
 [5.8        2.6        4.         1.2       ]
 [5.85047619 2.3        3.3        1.        ]
 [5.6        2.7        4.2        1.3       ]
 [5.85047619 3.         4.2        1.2       ]
 [5.85047619 2.9        4.2        1.3       ]
 [5.85047619 2.9        4.3        1.3       ]
 [5.1        2.5        3.         1.1       ]
 [5.7        2.8        4.1        1.3       ]
 [6.3        3.3        6.         2.5       ]
 [5.8        2.7        5.1        1.9       ]
 [5.85047619 3.         5.9        2.1       ]
 [6.3        2.9        5.6        1.8       ]
 [5.85047619 3.         5.8        2.2       ]
 [5.85047619 3.         6.6        2.1       ]
 [4.9        2.5        4.5        1.7       ]
 [7.3        2.9        6.3        1.8       ]
 [5.85047619 2.5        5.8        1.8       ]
 [5.85047619 3.6        6.1        2.5       ]
 [5.85047619 3.2        5.1        2.        ]
 [6.4        2.7        5.3        1.9       ]
 [5.85047619 3.         5.5        2.1       ]
 [5.85047619 2.5        5.         2.        ]
 [5.85047619 2.8        5.1        2.4       ]
 [6.4        3.2        5.3        2.3       ]
 [6.5        3.         5.5        1.8       ]
 [7.7        3.8        6.7        2.2       ]
 [7.7        2.6        6.9        2.3       ]
 [6.         2.2        5.         1.5       ]
 [5.85047619 3.2        5.7        2.3       ]
 [5.85047619 2.8        4.9        2.        ]
 [7.7        2.8        6.7        2.        ]
 [6.3        2.7        4.9        1.8       ]
 [6.7        3.3        5.7        2.1       ]
 [7.2        3.2        6.         1.8       ]
 [6.2        2.8        4.8        1.8       ]
 [6.1        3.         4.9        1.8       ]
 [6.4        2.8        5.6        2.1       ]
 [7.2        3.         5.8        1.6       ]
 [7.4        2.8        6.1        1.9       ]
 [7.9        3.8        6.4        2.        ]
 [6.4        2.8        5.6        2.2       ]
 [6.3        2.8        5.1        1.5       ]
 [5.85047619 2.6        5.6        1.4       ]
 [7.7        3.         6.1        2.3       ]
 [6.3        3.4        5.6        2.4       ]
 [6.4        3.1        5.5        1.8       ]
 [6.         3.         4.8        1.8       ]
 [6.9        3.1        5.4        2.1       ]
 [5.85047619 3.1        5.6        2.4       ]
 [6.9        3.1        5.1        2.3       ]
 [5.8        2.7        5.1        1.9       ]
 [6.8        3.2        5.9        2.3       ]
 [6.7        3.3        5.7        2.5       ]
 [6.7        3.         5.2        2.3       ]
 [6.3        2.5        5.         1.9       ]
 [5.85047619 3.         5.2        2.        ]
 [6.2        3.4        5.4        2.3       ]
 [5.9        3.         5.1        1.8       ]]

In [20]:
from sklearn import linear_model
iris_MAR_regression = iris_MAR.copy()

In [21]:
iris_MAR_regression_model = iris_MAR_regression.copy().dropna()

model = linear_model.LinearRegression()
Xs = iris_MAR_regression_model['sepal width (cm)'].values.reshape(-1, 1)
ys = iris_MAR_regression_model['sepal length (cm)'].values.reshape(-1, 1)
model.fit(X = Xs, y = ys)

null_index = iris_MAR_regression['sepal length (cm)'].isnull()

na_result = model.predict(iris_MAR_regression[null_index]['sepal width (cm)'].values.reshape(-1, 1))


iris_MAR_regression.loc[iris_MAR_regression['sepal length (cm)'].isnull(), 'sepal length (cm)'] = na_result.reshape(len(na_result),)

iris_MAR_regression

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             5.100000               3.5                1.4               0.2
1             4.900000               3.0                1.4               0.2
2             4.700000               3.2                1.3               0.2
3             4.600000               3.1                1.5               0.2
4             5.714692               3.6                1.4               0.2
..                 ...               ...                ...               ...
145           6.700000               3.0                5.2               2.3
146           6.300000               2.5                5.0               1.9
147           5.857028               3.0                5.2               2.0
148           6.200000               3.4                5.4               2.3
149           5.900000               3.0                5.1               1.8

[150 rows x 4 columns]

In [22]:
from sklearn.impute import KNNImputer
iris_MAR_knn = iris_MAR.copy()

In [23]:
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")

knn_imputer.fit_transform(iris_MAR_knn)

array([[5.1 , 3.5 , 1.4 , 0.2 ],
       [4.9 , 3.  , 1.4 , 0.2 ],
       [4.7 , 3.2 , 1.3 , 0.2 ],
       [4.6 , 3.1 , 1.5 , 0.2 ],
       [5.  , 3.6 , 1.4 , 0.2 ],
       [5.4 , 3.9 , 1.7 , 0.4 ],
       [4.6 , 3.4 , 1.4 , 0.3 ],
       [5.  , 3.4 , 1.5 , 0.2 ],
       [4.4 , 2.9 , 1.4 , 0.2 ],
       [4.9 , 3.1 , 1.5 , 0.1 ],
       [5.4 , 3.7 , 1.5 , 0.2 ],
       [5.05, 3.4 , 1.6 , 0.2 ],
       [4.8 , 3.  , 1.4 , 0.1 ],
       [4.3 , 3.  , 1.1 , 0.1 ],
       [5.8 , 4.  , 1.2 , 0.2 ],
       [5.3 , 4.4 , 1.5 , 0.4 ],
       [5.4 , 3.9 , 1.3 , 0.4 ],
       [5.05, 3.5 , 1.4 , 0.3 ],
       [5.25, 3.8 , 1.7 , 0.3 ],
       [5.1 , 3.8 , 1.5 , 0.3 ],
       [5.05, 3.4 , 1.7 , 0.2 ],
       [5.1 , 3.7 , 1.5 , 0.4 ],
       [4.6 , 3.6 , 1.  , 0.2 ],
       [5.05, 3.3 , 1.7 , 0.5 ],
       [5.05, 3.4 , 1.9 , 0.2 ],
       [5.  , 3.  , 1.6 , 0.2 ],
       [5.  , 3.4 , 1.6 , 0.4 ],
       [5.05, 3.5 , 1.5 , 0.2 ],
       [5.2 , 3.4 , 1.4 , 0.2 ],
       [4.7 , 3.2 , 1.6 , 0.2 ],
       [4.8 , 3.1 , 1.6 , 0.2 ],
       [4.8 , 3.4 , 1.5 , 0.4 ],
       [5.2 , 4.1 , 1.5 , 0.1 ],
       [5.5 , 4.2 , 1.4 , 0.2 ],
       [4.9 , 3.1 , 1.5 , 0.2 ],
       [4.55, 3.2 , 1.2 , 0.2 ],
       [5.5 , 3.5 , 1.3 , 0.2 ],
       [4.9 , 3.6 , 1.4 , 0.1 ],
       [4.85, 3.  , 1.3 , 0.2 ],
       [5.1 , 3.4 , 1.5 , 0.2 ],
       [5.  , 3.5 , 1.3 , 0.3 ],
       [4.6 , 2.3 , 1.3 , 0.3 ],
       [4.4 , 3.2 , 1.3 , 0.2 ],
       [5.05, 3.5 , 1.6 , 0.6 ],
       [5.1 , 3.8 , 1.9 , 0.4 ],
       [4.8 , 3.  , 1.4 , 0.3 ],
       [5.1 , 3.8 , 1.6 , 0.2 ],
       [4.6 , 3.2 , 1.4 , 0.2 ],
       [5.3 , 3.7 , 1.5 , 0.2 ],
       [4.9 , 3.3 , 1.4 , 0.2 ],
       [6.35, 3.2 , 4.7 , 1.4 ],
       [6.4 , 3.2 , 4.5 , 1.5 ],
       [6.9 , 3.1 , 4.9 , 1.5 ],
       [5.5 , 2.3 , 4.  , 1.3 ],
       [6.5 , 2.8 , 4.6 , 1.5 ],
       [5.7 , 2.8 , 4.5 , 1.3 ],
       [6.3 , 3.3 , 4.7 , 1.6 ],
       [4.9 , 2.4 , 3.3 , 1.  ],
       [6.6 , 2.9 , 4.6 , 1.3 ],
       [5.2 , 2.7 , 3.9 , 1.4 ],
       [5.  , 2.  , 3.5 , 1.  ],
       [6.1 , 3.  , 4.2 , 1.5 ],
       [6.  , 2.2 , 4.  , 1.  ],
       [6.1 , 2.9 , 4.7 , 1.4 ],
       [5.5 , 2.9 , 3.6 , 1.3 ],
       [6.7 , 3.1 , 4.4 , 1.4 ],
       [5.6 , 3.  , 4.5 , 1.5 ],
       [5.8 , 2.7 , 4.1 , 1.  ],
       [6.2 , 2.2 , 4.5 , 1.5 ],
       [5.6 , 2.5 , 3.9 , 1.1 ],
       [5.9 , 3.2 , 4.8 , 1.8 ],
       [5.75, 2.8 , 4.  , 1.3 ],
       [6.3 , 2.5 , 4.9 , 1.5 ],
       [6.1 , 2.8 , 4.7 , 1.2 ],
       [6.4 , 2.9 , 4.3 , 1.3 ],
       [6.6 , 3.  , 4.4 , 1.4 ],
       [6.8 , 2.8 , 4.8 , 1.4 ],
       [6.  , 3.  , 5.  , 1.7 ],
       [5.5 , 2.9 , 4.5 , 1.5 ],
       [5.7 , 2.6 , 3.5 , 1.  ],
       [5.5 , 2.4 , 3.8 , 1.1 ],
       [5.5 , 2.4 , 3.7 , 1.  ],
       [5.8 , 2.7 , 3.9 , 1.2 ],
       [6.  , 2.7 , 5.1 , 1.6 ],
       [5.4 , 3.  , 4.5 , 1.5 ],
       [6.35, 3.4 , 4.5 , 1.6 ],
       [6.5 , 3.1 , 4.7 , 1.5 ],
       [6.3 , 2.3 , 4.4 , 1.3 ],
       [5.6 , 3.  , 4.1 , 1.3 ],
       [5.5 , 2.5 , 4.  , 1.3 ],
       [5.65, 2.6 , 4.4 , 1.2 ],
       [6.35, 3.  , 4.6 , 1.4 ],
       [5.8 , 2.6 , 4.  , 1.2 ],
       [4.95, 2.3 , 3.3 , 1.  ],
       [5.6 , 2.7 , 4.2 , 1.3 ],
       [6.  , 3.  , 4.2 , 1.2 ],
       [6.05, 2.9 , 4.2 , 1.3 ],
       [6.5 , 2.9 , 4.3 , 1.3 ],
       [5.1 , 2.5 , 3.  , 1.1 ],
       [5.7 , 2.8 , 4.1 , 1.3 ],
       [6.3 , 3.3 , 6.  , 2.5 ],
       [5.8 , 2.7 , 5.1 , 1.9 ],
       [7.25, 3.  , 5.9 , 2.1 ],
       [6.3 , 2.9 , 5.6 , 1.8 ],
       [6.6 , 3.  , 5.8 , 2.2 ],
       [7.5 , 3.  , 6.6 , 2.1 ],
       [4.9 , 2.5 , 4.5 , 1.7 ],
       [7.3 , 2.9 , 6.3 , 1.8 ],
       [6.85, 2.5 , 5.8 , 1.8 ],
       [6.55, 3.6 , 6.1 , 2.5 ],
       [6.4 , 3.2 , 5.1 , 2.  ],
       [6.4 , 2.7 , 5.3 , 1.9 ],
       [6.65, 3.  , 5.5 , 2.1 ],
       [6.05, 2.5 , 5.  , 2.  ],
       [6.8 , 2.8 , 5.1 , 2.4 ],
       [6.4 , 3.2 , 5.3 , 2.3 ],
       [6.5 , 3.  , 5.5 , 1.8 ],
       [7.7 , 3.8 , 6.7 , 2.2 ],
       [7.7 , 2.6 , 6.9 , 2.3 ],
       [6.  , 2.2 , 5.  , 1.5 ],
       [6.75, 3.2 , 5.7 , 2.3 ],
       [6.25, 2.8 , 4.9 , 2.  ],
       [7.7 , 2.8 , 6.7 , 2.  ],
       [6.3 , 2.7 , 4.9 , 1.8 ],
       [6.7 , 3.3 , 5.7 , 2.1 ],
       [7.2 , 3.2 , 6.  , 1.8 ],
       [6.2 , 2.8 , 4.8 , 1.8 ],
       [6.1 , 3.  , 4.9 , 1.8 ],
       [6.4 , 2.8 , 5.6 , 2.1 ],
       [7.2 , 3.  , 5.8 , 1.6 ],
       [7.4 , 2.8 , 6.1 , 1.9 ],
       [7.9 , 3.8 , 6.4 , 2.  ],
       [6.4 , 2.8 , 5.6 , 2.2 ],
       [6.3 , 2.8 , 5.1 , 1.5 ],
       [6.75, 2.6 , 5.6 , 1.4 ],
       [7.7 , 3.  , 6.1 , 2.3 ],
       [6.3 , 3.4 , 5.6 , 2.4 ],
       [6.4 , 3.1 , 5.5 , 1.8 ],
       [6.  , 3.  , 4.8 , 1.8 ],
       [6.9 , 3.1 , 5.4 , 2.1 ],
       [6.5 , 3.1 , 5.6 , 2.4 ],
       [6.9 , 3.1 , 5.1 , 2.3 ],
       [5.8 , 2.7 , 5.1 , 1.9 ],
       [6.8 , 3.2 , 5.9 , 2.3 ],
       [6.7 , 3.3 , 5.7 , 2.5 ],
       [6.7 , 3.  , 5.2 , 2.3 ],
       [6.3 , 2.5 , 5.  , 1.9 ],
       [6.4 , 3.  , 5.2 , 2.  ],
       [6.2 , 3.4 , 5.4 , 2.3 ],
       [5.9 , 3.  , 5.1 , 1.8 ]])